stages:
  - test

.something: &prepare_repo
  - meson setup build

code_check:
  stage: test
  before_script:
    *prepare_repo
  script:
    cppcheck YGP/ XGP/ --enable=all
  only:
    - master

test:
  stage: test
  before_script:
    - *prepare_repo
    - meson compile -C build
  script:
    - meson test -C build --print-errorlogs
