//$Id: CDirSrch.idl,v 1.9 2008/06/08 12:32:07 markus Rel $

//PROJECT     : General
//SUBSYSTEM   : CORBA
//REFERENCES  :
//TODO        :
//BUGS        :
//REVISION    : $Revision: 1.9 $
//AUTHOR      : Markus Schwab
//CREATED     : 7.1.2001
//COPYRIGHT   : Copyright (C) 2001 - 2004, 2008

// This file is part of libYGP.
//
// libYGP is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// libYGP is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with libYGP.  If not, see <http://www.gnu.org/licenses/>.

interface CFile {
   // Retrieve information
   string        path ();
   string        name ();
   unsigned long size ();
   string        time ();
   unsigned long attributes ();

   // File-type
   boolean isDirectory ();
   boolean isExecuteable ();
   boolean isUserExec ();

   // Compare
   short compare (in string name);
   short compareObject (in CFile other);

   void exit ();
};

interface CDirectorySearch {
   void setSearchValue (in string file);

   CFile find (in unsigned long attr);
   CFile next ();

   boolean isValid ();

   string getSearchValue ();
   string getDirectory ();
   string getFileSpec ();

   void exit ();

   const unsigned long FILE_NORMAL    = 1;
   const unsigned long FILE_READONLY  = 2;
   const unsigned long FILE_DIRECTORY = 4;
   const unsigned long FILE_HIDDEN    = 8;
};
