//$Id: CDirSrch.idl,v 1.5 2002/07/08 03:31:00 markus Exp $

//PROJECT     : General
//SUBSYSTEM   : CORBA
//REFERENCES  :
//TODO        :
//BUGS        :
//REVISION    : $Revision: 1.5 $
//AUTHOR      : Markus Schwab
//CREATED     : 7.1.2001
//COPYRIGHT   : Anticopyright (A) 2001

// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 2 of the License, or
// (at your option) any later version.

// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

interface CFile {
   // Retrieve information
   string        path ();
   string        name ();
   unsigned long size ();
   string        time ();
   unsigned long attributes ();

   // File-type
   boolean isDirectory ();
   boolean isExecuteable ();
   boolean isUserExec ();

   // Compare
   short compare (in string name);
   short compareObject (in CFile other);
};

interface CDirectorySearch {
   CFile find (in string file, in unsigned long attr);
   CFile findnext ();

   string getSearchValue ();

   const unsigned long FILE_NORMAL    = 1;
   const unsigned long FILE_READONLY  = 2;
   const unsigned long FILE_DIRECTORY = 4;
   const unsigned long FILE_HIDDEN    = 8;
};
